#!/bin/bash
set -euo pipefail

INSTALL_ROOT=/opt/hiddify-manager
MARKER="$INSTALL_ROOT/.safeline-smoke-install"

if [ ! -f "$MARKER" ]; then
    echo "Refusing to apply the SafeLine smoke profile without $MARKER" >&2
    exit 78
fi

source "$INSTALL_ROOT/common/utils.sh"
activate_python_venv

# Keep the first integration test focused on the required VLESS Reality path.
# Every secret below remains generated by Panel on this VPS; only feature flags
# and the inherited core selector are changed.
declare -a SETTINGS=(
    "auto_update=false"
    "core_type=xray"
    "vless_enable=true"
    "reality_enable=true"
    "warp_mode=disable"
    "wireguard_enable=false"
    "telegram_enable=false"
    "dnstt_enable=false"
    "speed_test=false"
    "hiddifycli_enable=false"
    "ssh_server_enable=false"
    "ssfaketls_enable=false"
)

for setting in "${SETTINGS[@]}"; do
    key="${setting%%=*}"
    value="${setting#*=}"
    hiddify-panel-cli set-setting --key "$key" --val "$value" >/dev/null
done

rm -f /etc/cron.d/hiddify_auto_update
rm -f /etc/cron.d/hiddify_daily
service cron reload >/dev/null 2>&1 || true

echo "Applied pinned SafeLine VLESS Reality smoke-test profile."
